id: P003273
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22235
  title: ཟློས་གར་དུས་ཀྱི་མེ་ལོང་།
  author: ''
  volumes:
    8612963d0a1a482dbcc4a2d5a9603c9e:
      image_group_id: I1KG22291
      title: ''
      volume_number: 1
      total_pages: 74
      base_file: v001.txt
