id: I7102B194
legacy_id: P003273
ocr_import_info:
  bdrc_scan_id: W1KG22235
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T12:21:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T07:10:19.883113+00:00'
last_modified: 2022-08-27 15:10:30.568911
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22235
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22235
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཟློས་གར་དུས་ཀྱི་མེ་ལོང་།
  author: ལ་དྭགས་བཀྲ་ཤིས་རབ་རྒྱས།
statistics:
  ocr_word_mean_confidence_index: 0.9542851786985227
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG22291:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22291
      total_pages: 74
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22291.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9542851786985227
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
